### ISSUE TITLE
do not support arr

### ISSUE THREAD

**Issue by builden** [kawanet/qs-lite#1]
such as:

``` js
var querystring = require('querystring');
var qs = require('qs-lite');
var assert = require('assert');
var obj = {
  arr = [1, 2, 3]
};

assert(qs.stringify(obj) === querystring.stringify(obj));
```

**Comment by kawanet** [comment]
Right. It supports the plain old style of string-to-string key value pairs but does NOT support encoding any Objects including Array.

(a) stringify the array.

```
var obj = {
  arr = [1, 2, 3].join(",")
};
```

Or (b) use JSON for complex data encoding, instead.
